version: '3.7'
services:
    database:
        container_name: database
        image: 'library/mysql:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: main
        ports:
            - '3306'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        depends_on:
            - database
        environment:
            PMA_HOST: database
        restart: always
        ports:
            - "8080:80"
