version: "3.7"
services:
    database:
        image: "mysql:8.0"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=main
            - MYSQL_USER=test
            - MYSQL_PASSWORD=password
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        depends_on:
            - database
        environment:
            PMA_HOST: database
        restart: always
        ports:
            - "8080:80"

    webserver:
        container_name: webserver
        image: "nginx:alpine"
        working_dir: /app
        volumes:
            - ".:/app"
            - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "80:80"

    php-fpm:
        container_name: php
        depends_on:
            - database
        build: docker/php-fpm
        working_dir: /app
        volumes:
            - ".:/app"
            - "./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini"
